# Generated by Django 3.2.15 on 2022-09-05 02:32

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=places.fields.PlacesField(max_length=255),
        ),
        migrations.AlterField(
            model_name='office',
            name='location',
            field=places.fields.PlacesField(max_length=255),
        ),
    ]
