# Generated by Django 3.2.15 on 2022-09-05 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20220905_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='office',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
