# Generated by Django 3.2.15 on 2022-09-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20220905_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Phone number must be in international format, e.g. +571234567890', max_length=16),
        ),
    ]
